version: "#{build}"
image: Visual Studio 2017
configuration: Release

before_build:
- ps: dotnet --info
- ps: dotnet restore --verbosity detailed

build:
  verbosity: minimal

test_script:
- ps: dotnet test -c $env:CONFIGURATION ./test/Yargon.Parser.Tests/Yargon.Parser.Tests.csproj
- ps: dotnet test -c $env:CONFIGURATION ./test/Yargon.Parser.Sdf.Tests/Yargon.Parser.Sdf.Tests.csproj
