version: "#{build}"
os: Visual Studio 2015
configuration: Release

before_build:
- del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
- nuget restore
